/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('antd')['Button']
  const Input: typeof import('antd')['Input']
  const Layout: typeof import('antd')['Layout']
  const MailOutlined: typeof import('@ant-design/icons')['MailOutlined']
  const Menu: typeof import('antd')['Menu']
  const MenuProps: typeof import('antd')['MenuProps']
  const Pagination: typeof import('antd')['Pagination']
  const QueryClient: typeof import('@tanstack/react-query')['QueryClient']
  const SearchOutlined: typeof import('@ant-design/icons')['SearchOutlined']
  const Select: typeof import('antd')['Select']
  const SmileOutlined: typeof import('@ant-design/icons')['SmileOutlined']
  const Space: typeof import('antd')['Space']
  const Table: typeof import('antd')['Table']
  const Tag: typeof import('antd')['Tag']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const message: typeof import('antd')['message']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImmer: typeof import('use-immer')['useImmer']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMutation: typeof import('@tanstack/react-query')['useMutation']
  const useQuery: typeof import('@tanstack/react-query')['useQuery']
  const useQueryClient: typeof import('@tanstack/react-query')['useQueryClient']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
